server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phonemanagerdb
    username: root
    password: Lienltw99@@
    dirver-class-name: com.mysql.jdbc.Driver
  application:
    name: phonemanagerdb
  jpa:
    hibernate:
      ddl-auto: update

